RPC_SERVER : {
    'HOST': 'localhost',
    'PORT': 4040
}

RECOMMEND_SERVER : {
    'HOST': 'localhost',
    'PORT': 5050,
    'MAX_PREFER_RATIO': 15,
    'UNCLASSIFIED_RATIO': 1
}

NEWS_CLASSIFIER_SERVER : {
    'HOST': 'localhost',
    'PORT': 6060
}

MONGO : {
    'HOST': 'localhost',
    'PORT': '27017',
    'FIND_AMOUNT': 100,
    'NEWS_DB': 'test',
    'NEWS_COLLECTION': 'news',
    'USER_DB': 'user',
    'USER_PREFERENCES': 'preferences',
    'URI': 'mongodb://localhost/user'
}

NEWSAPI : {
    'KEY': '4ed99fbbbee04fdb9b1a8426882682cc',
    'API_BASE': 'https://newsapi.org/v1/articles',
    'DEFAULT_SOURCES': [
        'bbc-news',
        'bbc-sport',
        'bloomberg',
        'business-insider',
        'buzzfeed',
        'cnn',
        'engadget',
        'entertainment-weekly',
        'google-news',
        'ign',
        'the-economist',
        'the-wall-street-journal',
        'the-washington-post',
        'the-verge',
        'the-new-york-times'
    ],
    'DEFUALT_SORT': 'top'
}

QUE_MONITOR_SCRAPER : {
    'URI': 'amqp://uneggxcr:eElS-gADqt1sv8niqv6uzKaiCKT2mnhP@donkey.rmq.cloudamqp.com/uneggxcr',
    'NAME': 'monitor_scraper'
}

QUE_SCRAPER_DEDUPER : {
    'URI': 'amqp://llkcvaiq:98buUaysrg1umBoqAdVRfb9nAngHtsxq@donkey.rmq.cloudamqp.com/llkcvaiq',
    'NAME': 'scraper_deduper'
}

QUE_LOGGER : {
    'URI': 'amqp://siodttgr:2oPzhSjBUG0nZSz9hJnSg5a1b1TUIZN0@donkey.rmq.cloudamqp.com/siodttgr',
    'NAME': 'logger'
}

SLEEP : {
    'MONITOR': 60.0,
    'MONITOR_INCREASE_RATE': 1.5,
    'MONITOR_DECREASE_RATE': 0.5,
    'SCRAPER': 5.0,
    'SCRAPER_INCREASE_RATE': 1.5,
    'SCRAPER_DECREASE_RATE': 0.5,
    'DEDUPER': 5.0,
    'DEDUPER_INCREASE_RATE': 1.5,
    'DEDUPER_DECREASE_RATE': 0.5,
    'LOGGER' : 1.0,
    'LOGGER_INCREASE_RATE': 1.5,
    'LOGGER_DECREASE_RATE': 0.5,
    'MIN': 0.1,
    'MAX': 1800.0
}

PAGINATION : 10

JWT_SECRET : 'a secret phrase!!'

# 3600*24=86400
REDIS : {
    'HOST': 'localhost',
    'PORT': 6379,
    'NEWS_EXPIRATION': 86400,
    'DIGEST_EXPIRATION': 6
}

TFIDF : {
    'SAME_NEWS_SIMILARITY_THRESHOLD': 0.85
}

TIME_DECAY_MODEL : {
    'ALPHA' : 0.1
}

NEWSCLASSES : {
    "list" : [
        "Colleges & Schools",
        "Environmental",
        "World",
        "Entertainment",
        "Media",
        "Politics & Government",
        "Regional News",
        "Religion",
        "Sports",
        "Technology",
        "Traffic",
        "Weather",
        "Economic & Corp",
        "Advertisements",
        "Crime",
        "Other",
        "Magazine"
    ],
    "map" : {
        '1' : 'Colleges & Schools',
        '2' : 'Environmental',
        '3' : 'World',
        '4' : 'Entertainment',
        '5' : 'Media',
        '6' : 'Politics & Government',
        '7' : 'Regional News',
        '8' : 'Religion',
        '9' : 'Sports',
        '10' : 'Technology',
        '11' : 'Traffic',
        '12' : 'Weather',
        '13' : 'Economic & Corp',
        '14' : 'Advertisements',
        '15' : 'Crime',
        '16' : 'Other',
        '17' : 'Magazine'
    },
    "reverse_map" : {
        "Colleges & Schools" : "1",
        "Environmental" : "2",
        "World" : "3",
        "Entertainment" : "4",
        "Media" : "5",
        "Politics & Government" : "6",
        "Regional News" : "7",
        "Religion" : "8",
        "Sports" : "9",
        "Technology" : "10",
        "Traffic" : "11",
        "Weather" : "12",
        "Economic & Corp" : "13",
        "Advertisements" : "14",
        "Crime" : "15",
        "Other" : "16",
        "Magazine" : "17"
    }
}
